sudo: required
services:
  - docker

before_install:
  - docker build -t romanchitto/docker-appsy -f Dockerfile.dev .

script:
  - docker run romanchitto/docker-appsy npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "todo-docker"
  env: "TodoDocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-510870579936"
  bucket_path: "todo-docker"
  on:
    branch: master
  access_key_id: $AWS_KEY_ID
  secret_access_key: 
    secure: $AWS_SECRET